### ISSUE TITLE
No student list loads forever

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#17]
Summary: Clicking on student list with no students in list causes it to load indefinitely and throws 404 error.

Description: I clicked on student list before adding any students to the list. The page shows a loading message that never disappears and throws
‘api/pullstudentlist:1 Failed to load resource: the server responded with a status of 404 (Not Found)
StudentTable.js:20 SyntaxError: Unexpected token < in JSON at position 0 "failed to fetch"’

Severity: Low

Suggestions/Comments: This should be fairly easy to fix. Just check the size of the array before pulling it. If it is 0, display a message like ‘There are no students’ before pulling the data.

**Comment by JinwooOh** [comment]
We haven't implemented StudenList API.

**Comment by JinwooOh** [comment]
Deleted Student List from Navigation bar
