### ISSUE TITLE
Add description to Question Number field

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#24]
Summary: What Question Number field in create test is unclear and allows negative numbers.

Description: It took me way too long to discover that this number affects the number of questions pulled when the pull button is hit. You can also insert negative numbers which seems like an oversight. It takes the absolute value of the input but still, it doesn’t make sense that this is allowed.

Severity: Medium

Suggestions/Comments: Change the wording of the field to something like Number of Questions to Pull. This will be much more clear to the user what is happening. Also use validators in either the front or back end to not accept negative numbers.

**Comment by JinwooOh** [comment]
Changed desc to "Number of Questions to Pull"
