### ISSUE TITLE
Nowhere to set test difficulty

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#25]
Summary: Test difficulty can’t be set

Description: There is a field for the difficulty of the test in the exam list but I can find no way to set this difficulty. You also state in the documents that this needs to be present.

Severity: Low

Suggestions/Comments: Add another field to the create test and edit tests. Maybe create a drop down with options such as Hard or Easy. Store the information in a way similar to the way you store the name of the test. Then display this information on relevant pages.

**Comment by JinwooOh** [comment]
Deleted difficulty field
