### ISSUE TITLE
What do multiple choice radio buttons do?

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#28]
Summary: What multiple choice radio buttons do is unclear.

Description: There are two options for multiple choice questions on the Create Test page. The same questions appear no matter which is selected so I’m not sure what they indicate.

Severity: Low

Suggestions/Comments: Change the wording of the buttons to describe what they actually do or label your question structures by whether they are multiple choice questions or not and only pull appropriate questions.

**Comment by JinwooOh** [comment]
We originally planned to implement a multiple choice filter to query data from the DB. 

We decide to delete this functionality.
