### ISSUE TITLE
Extra rows on Exam List page

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#33]
Summary: Creating a new test causes display issues on the Exam List page.

Description: When a user creates a new test on the Create Test page then immediately goes to the Exam List page, six rows are showed instead of five as should be. Refreshing the page doesn’t fix this but switching to ten rows and back to five does.

Severity: Low

Suggestions/Comments: I really need to know more about how you grab and display tests to see what is going wrong here. You could make sure everything refreshes when you go to this page or maybe update the row number for a quick fix immediately on routing to the page.

**Comment by JinwooOh** [comment]
Changed to default page size to 10
