### ISSUE TITLE
All questions can be removed during edit

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#37]
Summary: Editing a test allows for removal of all questions.

Description: When creating a test, the site doesn’t allow the creation of tests with no questions. When editing a test, a user can remove all questions. This is inconsistent.

Severity: Low

Suggestions/Comments: Before saving and updating the test, check to see how many questions there are. If there are zero, don’t update and display an error saying that there are no questions in this test.

**Comment by JinwooOh** [comment]
Fixed: if an exam has less than 2 questions, it alerts an error message
