### ISSUE TITLE
CSV import not working

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#39]
Summary: Importing a .csv file throws an error.

Description: I tried to import a simple .csv file to the Import Questions page and an error was thrown. I’m not sure if I’m doing something wrong. The .csv was created in excel.

Stack trace: ImportQCSV.js:38 POST http://localhost:3000/api/importCSV net::ERR_EMPTY_RESPONSE
ImportQCSV._this.handleFileRead @ ImportQCSV.js:38
FileReader (async)
ImportQCSV._this.handleFileChosen @ ImportQCSV.js:54
onChange @ ImportQCSV.js:66
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4820
batchedUpdates$1 @ react-dom.development.js:18932
batchedUpdates @ react-dom.development.js:2150
dispatchEvent @ react-dom.development.js:4899
index.js:2178 fetch error at importCSV TypeError: Failed to fetch

Severity: High

Suggestions/Comments: There is some problem reading the .csv file. Do csv’s need to be formatted in a particular way? No error is displayed to the user so something should be shown when this error occurs. A help option or page would be great in this case to describe what csv’s should look like and what possible errors are when adding them.

**Comment by maggiemarxen** [comment]
CSV's must be formatted according to client specification, which does work correctly.
