### ISSUE TITLE
Add question page not working or confusing

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#40]
Summary: Add Question and Import Image buttons doesn’t seem to work.

Description: I can’t seem to get any response from the Add Question or Import Image buttons no matter what I put in fields on the Import Question page. This could be related to the edit questions window not working.

Severity: Critical

Suggestions/Comments: Display something acknowledging that the button has been pressed. Then display what is needed still in order to actually add a question. I don’t know if it just hasn’t been implemented or if I the user is doing something wrong. Add more instructions.

**Comment by ceiselm** [comment]
Fixed by Jinwoo and added additional wording to the user alert
