### ISSUE TITLE
Question List attributes don't match specifications

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#41]
Summary: Question List page has columns for attributes that tests have but questions don’t

Description: The Question List page has columns for Course Number, Test Difficulty, Number of Questions, and Time Limit. These don’t make sense to be paired with individual questions and are clearly meant for tests which is confusing for users.

Severity: Low

Suggestions/Comments: Remove these columns and maybe instead add columns for number of options or difficulty of question rather than copying and pasting the exam format.

**Comment by JinwooOh** [comment]
Fixex: deleted unnecessary cols
