### ISSUE TITLE
Making course number a string breaks exams in database

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#43]
Summary: Changing course number to letters deleted all tests.

Description: I tried editing a new test by changing the course number to letters. The system allowed this and said I successfully updated the test. Git bash said reported that the app crashed - waiting for file changes before restarting followed by a proxy error. There is no indication of this on the front end. When I refreshed the page, all tests were missing, new tests could not be created, and exams couldn’t be taken.

Severity: Critical

Suggestions/Comments: The website is pretty much broken at this point from what occurred. Make absolute certain to prevent users from entering letters into the course number field in a similar way that you handle time limits for tests. It would also be wise to do error checking in the backend. If the received data isn’t an integer, stop and throw an error to the user before allowing the system to crash.

**Comment by ceiselm** [comment]
Added additional front-end warning to user and an additional constraints on the back-end for both Course Number and Time Limit in the Exam List tab.

**Comment by JinwooOh** [comment]
merged into an issues branch. I made a small change that we can only type number for a course number field.
