### ISSUE TITLE
Readability of Take Exam page

### ISSUE THREAD

**Issue by bdkinzer** [JinwooOh/CS200-testing-service#49]
Summary: Test answers in Take Exams page are very hard to read.

Description: Test answers are very light grey on a white background making them hard to read. This is bad on a usability standpoint because it may cause mistakes.

Severity: Medium

Suggestions/Comments: Try putting bold or strong tags around the answers in the html or change the color entirely.

**Comment by mingmei08** [comment]
change the color to red for clearly read
